### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by timmyers** [Fitbit/developer-bridge#148]
When trying to run `npx fitbit` as described here https://dev.fitbit.com/build/guides/command-line-interface/ on `"@fitbit/sdk-cli": "^1.7.1"`, get the following error after authenticating in browser.

```
❯ yarn fitbit
yarn run v1.22.4
$ /Users/tim/workspace/hotel/node_modules/.bin/fitbit
(node:27589) UnhandledPromiseRejectionWarning: DecodeError: Invalid value undefined supplied to : UserProfileResponse/user: { email: string, fullName: string }/fullName: string
    at /Users/tim/workspace/hotel/node_modules/@fitbit/jsonrpc-ts/lib/decode.js:32:19
    at /Users/tim/workspace/hotel/node_modules/@fitbit/jsonrpc-ts/node_modules/fp-ts/lib/Either.js:166:49
    at Object.pipe (/Users/tim/workspace/hotel/node_modules/@fitbit/jsonrpc-ts/node_modules/fp-ts/lib/pipeable.js:9:20)
    at /Users/tim/workspace/hotel/node_modules/@fitbit/jsonrpc-ts/lib/decode.js:31:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.userProfile [as default] (/Users/tim/workspace/hotel/node_modules/@fitbit/sdk-cli/lib/api/userProfile.js:13:22)
    at async main (/Users/tim/workspace/hotel/node_modules/@fitbit/sdk-cli/lib/cli.js:73:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27589) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Hexxeh** [comment]
Does this happen consistently, or just the once?

**Comment by timmyers** [comment]
Consistently, I am not able to get past the error.

**Comment by timmyers** [comment]
After some debugging I found it was failing because my user in the response had no `fullName` property.  I went to my profile on fitbit.com and realized the field in my profile was blank, added it there and it works now.
